---
title: retry
description: Run an async function retrying if it fails
since: 12.1.0
---

### Usage

The `_.retry` function allows you to run an async function and automagically retry it if it fails. Given the async func to run, an optional max number of retries (`r`), and an optional milliseconds to delay between retries (`d`), the given async function will be called, retrying `r` many times, and waiting `d` milliseconds between retries.

The `times` option defaults to `3`. The `delay` option (defaults to null) can specify milliseconds to sleep between attempts.

The `backoff` option is like delay but uses a function to sleep -- makes for easy exponential backoff.

```ts
import * as _ from 'radashi'

const api = {
  users: {
    async list() {
      if (Math.random() < 0.5) {
        throw new Error('Random error')
      }
      return []
    },
  },
}

await _.retry({}, api.users.list) // try 3 times before failing
await _.retry({ times: 10 }, api.users.list) // try 10 times before failing
await _.retry({ times: 2, delay: 1000 }, api.users.list) // try 2 times with 1 second delay

// exponential backoff
await _.retry({ backoff: i => 10 ** i }, api.users.list) // try 3 times with 10, 100, 1000 ms delay
```
